### ISSUE TITLE
Exception if cluster data doesn't contains key 'name' and not contains key 'vmid'

### ISSUE THREAD

**Issue by igrinon** [nbuchwitz/check_pve#50]
![image](https://github.com/nbuchwitz/check_pve/assets/2580220/816cdfbb-7b53-4006-a003-94b4fbd22466)

Traceback (most recent call last):
  File "/home/nagios/check_pve/check_pve.py", line 819, in <module>
    pve.check()
  File "/home/nagios/check_pve/check_pve.py", line 678, in check
    self.check_vm_status(idx, only_status=only_status)
  File "/home/nagios/check_pve/check_pve.py", line 208, in check_vm_status
    if vm['name'] == idx or vm['vmid'] == idx:
       ~~^^^^^^^^
KeyError: 'name'

Line 208
Change:
if vm['name'] == idx or vm['vmid'] == idx:
By:
if ('name' in vm and vm['name'] == idx) or ('vmid' in vm and vm['vmid'] == idx):

Thanks for this good code!!!

**Comment by nbuchwitz** [comment]
Thanks!
